name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
dream_company = input("Enter your dream company: ")
favorite_ai_tool = input("Enter your favorite AI tool: ")
print("===============================")
print("         About Me              ")
print("===============================")
print("Name:", name)
print("Age:", age)
print("City:", city)
print("Dream Company:", dream_company)
print("Favorite AI Tool:", favorite_ai_tool)
print("===============================")